services:
  postgres:
    image: postgres:15-alpine
    container_name: meteo_postgres_prod
    environment:
      POSTGRES_USER: ${PROD_DB_USER}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
      POSTGRES_DB: meteo_prod_db
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PROD_DB_USER} -d meteo_prod_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    container_name: meteo_api_prod
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL=postgres://${PROD_DB_USER}:${PROD_DB_PASSWORD}@postgres:5432/meteo_prod_db?sslmode=disable
      - ENVIRONMENT=production
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  ingester:
    build:
      context: .
      dockerfile: ./cmd/ingester/Dockerfile
    container_name: meteo_ingester_prod
    environment:
      - DATABASE_URL=postgres://${PROD_DB_USER}:${PROD_DB_PASSWORD}@postgres:5432/meteo_prod_db?sslmode=disable
      - ENVIRONMENT=production
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data_prod: